### PR TITLE
Milestone 5: Friendships v1

### PR DESCRIPTION
**Pull request by fivan18**
- [ ] Create a model with associations and all requested features for friendships.

### CODE REVIEW

**Review by mosaaleb — CHANGES_REQUESTED** [review]
### Well done team :clap:

Nice job adding friendship associations and adding tests for user and friendship models, but still we haven't added controllers or views requirements to mark this milestone as completed:

- [ ] User can invite friends



- [ ] User can see friendships requests, accept or reject them.





- [ ] Posts timeline includes posts written by logged-in user and their friends




- [ ] We still need to add integration tests using capybara for friendships functionality.




Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Comment by nikasulo** [comment]
# Error with friendship creation and deletion
Please consider the screenshot of errors below from running your test suite. Please look into them thoroughly, make the required changes and request another review. I wish you the very best and see you at the top! :rocket: 
screenshot
##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by wathigo — CHANGES_REQUESTED** [review]
### Approved!
Hello @fivan18 :wave: 
Great work so far :clap: 
Everything looks great now

**You may move on**

Good luck :four_leaf_clover: 
Simon Wathigo

**Pull request merged**
